In [1]:
import pandas as pd
url = 'C:/Users/Ahmadi/OneDrive/Desktop/datasets/2.1 Earnings_Manipulation220.csv'
df = pd.read_csv(url)
df.columns = df.columns.map(str.lower)
df

company name year ending      dsri       gmi       aqi        sgi  \
0               1   3/31/2014  1.624742  1.128927  7.185053   0.366211   
1               2   3/31/2009  1.000000  1.606492  1.004988  13.081433   
2               3   3/31/2008  1.000000  1.015607  1.241389   1.475018   
3               4   3/31/2014  1.486239  1.000000  0.465535   0.672840   
4               5   3/31/2010  1.000000  1.369038  0.637112   0.861346   
..            ...         ...       ...       ...       ...        ...   
215           216   3/31/2014  1.002026  0.998118 -0.917605   1.088962   
216           217   3/31/2014  0.909365  1.170298  1.971874   1.279013   
217           218   3/31/2014  0.937403  0.973292  1.131131   1.083577   
218           219   3/31/2014  1.044944  1.021424  4.437887   0.870790   
219           220   3/31/2014  0.958664  0.916985  0.999652   1.121524   

         depi      sgai      accr      levi  manipulator  
0    1.381519  1.624145 -0.166809  1.161082            1  
1    0.400000  5.198207  0.060475  0.986732            1  
2    1.169353  0.647671  0.036732  1.264305            1  
3    2.000000  0.092890  0.273434  0.680975            1  
4    1.454676  1.741460  0.123048  0.939047            1  
..        ...       ...       ...       ...          ...  
215  1.030527  1.076770 -0.001079  1.080009            0  
216  0.971605  0.985939 -0.035854  1.025102            0  
217  1.050011  0.959512 -0.095279  0.976332            0  
218  1.026489  1.060493 -0.157146  0.916070            0  
219  1.096174  0.927539 -0.145247  0.935351            0  

[220 rows x 11 columns]

In [2]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, cohen_kappa_score
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
def classify_report(ytest,y_pred):
    cm = confusion_matrix(ytest,y_pred)
    print("Confusion Matrix:\n",cm)
    error_rate = 1 - accuracy_score(ytest,y_pred)
    print("classification report:\n")
    print(classification_report(ytest,y_pred))
    print('Accuracy:\n',accuracy_score(ytest,y_pred))
    print('ErrorRate:\n',error_rate)
    print('Cohen Kappa score:\n',cohen_kappa_score(ytest,y_pred))


In [3]:
df['year ending'] = pd.to_datetime(df['year ending'])

# استخراج سال، ماه و روز و اضافه کردن آن‌ها به ابتدای دیتافریم
df.insert(1, 'year_ending', df['year ending'].dt.year)
df.insert(2, 'month_ending', df['year ending'].dt.month)
df.insert(3, 'day_ending', df['year ending'].dt.day)
df.drop(columns=['year ending'], inplace=True)
df

company name  year_ending  month_ending  day_ending      dsri       gmi  \
0               1         2014             3          31  1.624742  1.128927   
1               2         2009             3          31  1.000000  1.606492   
2               3         2008             3          31  1.000000  1.015607   
3               4         2014             3          31  1.486239  1.000000   
4               5         2010             3          31  1.000000  1.369038   
..            ...          ...           ...         ...       ...       ...   
215           216         2014             3          31  1.002026  0.998118   
216           217         2014             3          31  0.909365  1.170298   
217           218         2014             3          31  0.937403  0.973292   
218           219         2014             3          31  1.044944  1.021424   
219           220         2014             3          31  0.958664  0.916985   

          aqi        sgi      depi      sgai      accr      levi  manipulator  
0    7.185053   0.366211  1.381519  1.624145 -0.166809  1.161082            1  
1    1.004988  13.081433  0.400000  5.198207  0.060475  0.986732            1  
2    1.241389   1.475018  1.169353  0.647671  0.036732  1.264305            1  
3    0.465535   0.672840  2.000000  0.092890  0.273434  0.680975            1  
4    0.637112   0.861346  1.454676  1.741460  0.123048  0.939047            1  
..        ...        ...       ...       ...       ...       ...          ...  
215 -0.917605   1.088962  1.030527  1.076770 -0.001079  1.080009            0  
216  1.971874   1.279013  0.971605  0.985939 -0.035854  1.025102            0  
217  1.131131   1.083577  1.050011  0.959512 -0.095279  0.976332            0  
218  4.437887   0.870790  1.026489  1.060493 -0.157146  0.916070            0  
219  0.999652   1.121524  1.096174  0.927539 -0.145247  0.935351            0  

[220 rows x 13 columns]

In [4]:
# prediction with supervised algorithm

#input features
x = df.iloc[:,:12].values
#output class
y = df.iloc[:,12].values

#splitting the data into training and test
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2,random_state=0)

#1)naive bayes algorithm
#create a Gaussian naive bayes model
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
#fit a model
gnb.fit(xtrain,ytrain)
y_pred_gnb = gnb.predict(xtest)
classify_report(ytest,y_pred_gnb)

Confusion Matrix:
 [[36  0]
 [ 0  8]]
classification report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00         8

    accuracy                           1.00        44
   macro avg       1.00      1.00      1.00        44
weighted avg       1.00      1.00      1.00        44

Accuracy:
 1.0
ErrorRate:
 0.0
Cohen Kappa score:
 1.0


In [5]:
#2)KNN
from sklearn.neighbors import KNeighborsClassifier
# KNN model creation 
knn = KNeighborsClassifier(n_neighbors=5)

#fit model
knn.fit(xtrain,ytrain)
#perform predictions
y_pred_knn = knn.predict(xtest)

classify_report(ytest,y_pred_knn)

Confusion Matrix:
 [[36  0]
 [ 1  7]]
classification report:

              precision    recall  f1-score   support

           0       0.97      1.00      0.99        36
           1       1.00      0.88      0.93         8

    accuracy                           0.98        44
   macro avg       0.99      0.94      0.96        44
weighted avg       0.98      0.98      0.98        44

Accuracy:
 0.9772727272727273
ErrorRate:
 0.022727272727272707
Cohen Kappa score:
 0.9197080291970803


In [6]:
#ensembling technique AdaBoost
from sklearn.ensemble import AdaBoostClassifier
seed=7
num_trees = 100
model = AdaBoostClassifier(n_estimators=num_trees,random_state=seed)
model.fit(xtrain,ytrain)
y_pred_adb = model.predict(xtest)
classify_report(ytest,y_pred_adb)

Confusion Matrix:
 [[36  0]
 [ 0  8]]
classification report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00         8

    accuracy                           1.00        44
   macro avg       1.00      1.00      1.00        44
weighted avg       1.00      1.00      1.00        44

Accuracy:
 1.0
ErrorRate:
 0.0
Cohen Kappa score:
 1.0


In [7]:
# ensembling technique Gradient Boosting or XG Boost
from sklearn.ensemble import GradientBoostingClassifier
seed = 7
num_trees = 500
model = GradientBoostingClassifier(n_estimators=num_trees,random_state=seed,max_depth=20)
model.fit(xtrain,ytrain)
y_pred_adb = model.predict(xtest)
classify_report(ytest,y_pred_adb)

Confusion Matrix:
 [[36  0]
 [ 0  8]]
classification report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00         8

    accuracy                           1.00        44
   macro avg       1.00      1.00      1.00        44
weighted avg       1.00      1.00      1.00        44

Accuracy:
 1.0
ErrorRate:
 0.0
Cohen Kappa score:
 1.0
