In [1]:
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
url ='C:/Users/Ahmadi/OneDrive/Desktop/datasets/1.1 titanic.csv'
df = pd.read_csv(url).fillna(0)
#data cleaning , dropping column
df = df.drop('Name',axis=1)
df = df.drop('SexCode',axis=1)
#create mapper
PClass_mapper = {'1st':1,'2nd':2,'3rd':3}
gender_mapper = {'female':1,'male':2}

#replacing feature values with scale
df['PClass'] = df['PClass'].replace(PClass_mapper)
df['Sex'] = df['Sex'].replace(gender_mapper)
#replacing missing values of age with mean of age
df['Age'] = np.where(df['Age']==0,np.mean(df['Age']),df['Age'])
#input features
x = df.iloc[:,:3].values
#output class
y = df.iloc[:, 3].values

#creating KFold cross validation 
kf = KFold(n_splits=10,random_state=None,shuffle=False)
kf.get_n_splits(x,y)

#splitting data into train and test
for train_index, test_index in kf.split(x,y):
    print('TRAIN:',train_index,'TEST:',test_index)
    xtrain, xtest = x[train_index], y[test_index]
    ytrain, ytest = x[train_index], y[test_index]


TRAIN: [ 132  133  134 ... 1310 1311 1312] TEST: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131]
TRAIN: [   0    1    2 ... 1310 1311 1312] TEST: [132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149
 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185
 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203
 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221


In [2]:
import pandas as pd
import numpy as np
# prediction without applying KFold cross validation method
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
url ='C:/Users/Ahmadi/OneDrive/Desktop/datasets/1.1 titanic.csv'
df = pd.read_csv(url).fillna(0)
#data cleaning , dropping column
df = df.drop('Name',axis=1)
df = df.drop('SexCode',axis=1)
#create mapper
PClass_mapper = {'1st':1,'2nd':2,'3rd':3}
gender_mapper = {'female':1,'male':2}

#replacing feature values with scale
df['PClass'] = df['PClass'].replace(PClass_mapper)
df['Sex'] = df['Sex'].replace(gender_mapper)
#replacing missing values of age with mean of age
df['Age'] = np.where(df['Age']==0,np.mean(df['Age']),df['Age'])
#input features
x = df.iloc[:,:3].values
#output class
y = df.iloc[:, 3].values

#splitting the data into training and test
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3,random_state=0)
#preparing and fitting the RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10)
rfc.fit(xtrain,ytrain)
y_pred = rfc.predict(xtest)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, cohen_kappa_score
cm = confusion_matrix(ytest,y_pred)
print("Confusion Matrix:\n",cm)
error_rate = 1 - accuracy_score(ytest,y_pred)
print("classification report:\n")
print(classification_report(ytest,y_pred))
print('Accuracy:\n',accuracy_score(ytest,y_pred))
print('ErrorRate:\n',error_rate)
print('Cohen Kappa score:\n',cohen_kappa_score(ytest,y_pred))

Confusion Matrix:
 [[234  30]
 [ 49  81]]
classification report:

              precision    recall  f1-score   support

           0       0.83      0.89      0.86       264
           1       0.73      0.62      0.67       130

    accuracy                           0.80       394
   macro avg       0.78      0.75      0.76       394
weighted avg       0.79      0.80      0.80       394

Accuracy:
 0.799492385786802
ErrorRate:
 0.20050761421319796
Cohen Kappa score:
 0.5290646654764426


In [3]:
url ='C:/Users/Ahmadi/OneDrive/Desktop/datasets/1.1 titanic.csv'
df = pd.read_csv(url).fillna(0)
df

Name PClass    Age     Sex  \
0                      Allen, Miss Elisabeth Walton    1st  29.00  female   
1                       Allison, Miss Helen Loraine    1st   2.00  female   
2               Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                     Allison, Master Hudson Trevor    1st   0.92    male   
...                                             ...    ...    ...     ...   
1308                             Zakarian, Mr Artun    3rd  27.00    male   
1309                         Zakarian, Mr Maprieder    3rd  26.00    male   
1310                               Zenni, Mr Philip    3rd  22.00    male   
1311                               Lievens, Mr Rene    3rd  24.00    male   
1312                                 Zimmerman, Leo    3rd  29.00    male   

      Survived  SexCode  
0            1        1  
1            0        1  
2            0        0  
3            0        1  
4            1        0  
...        ...      ...  
1308         0        0  
1309         0        0  
1310         0        0  
1311         0        0  
1312         0        0  

[1313 rows x 6 columns]

In [5]:
# prediction by applying KFold cross validation method
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
url ='C:/Users/Ahmadi/OneDrive/Desktop/datasets/1.1 titanic.csv'
df = pd.read_csv(url).fillna(0)
#data cleaning , dropping column
df = df.drop('Name',axis=1)
df = df.drop('SexCode',axis=1)
#create mapper
PClass_mapper = {'1st':1,'2nd':2,'3rd':3}
gender_mapper = {'female':1,'male':2}

#replacing feature values with scale
df['PClass'] = df['PClass'].replace(PClass_mapper)
df['Sex'] = df['Sex'].replace(gender_mapper)
#replacing missing values of age with mean of age
df['Age'] = np.where(df['Age']==0,np.mean(df['Age']),df['Age'])
#input features
x = df.iloc[:,:3].values
#output class
y = df.iloc[:, 3].values

#creating KFold cross validation 
kf = KFold(n_splits=10,random_state=None,shuffle=False)
kf.get_n_splits(x,y)

#splitting data into train and test
i=1
for train_index, test_index in kf.split(x,y):
    #print('TRAIN:',train_index,'TEST:',test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('----------------------------')
    print('split No:',+i)
    print('----------------------------')
    i = i+1
#preparing and fitting the RF Model
    rfc = RandomForestClassifier(n_estimators=10)
    rfc.fit(x_train,y_train)
    y_pred = rfc.predict(x_test)
    from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, cohen_kappa_score
#confusion matrix
    cm = confusion_matrix(y_test,y_pred)
    print("Confusion Matrix:\n",cm)
    error_rate = 1 - accuracy_score(y_test,y_pred)
    print("classification report:\n")
    print(classification_report(y_test,y_pred))
    print('Accuracy:\n',accuracy_score(y_test,y_pred))
    print('ErrorRate:\n',error_rate)
    print('Cohen Kappa score:\n',cohen_kappa_score(y_test,y_pred))


----------------------------
split No: 1
----------------------------
Confusion Matrix:
 [[29 15]
 [25 63]]
classification report:

              precision    recall  f1-score   support

           0       0.54      0.66      0.59        44
           1       0.81      0.72      0.76        88

    accuracy                           0.70       132
   macro avg       0.67      0.69      0.68       132
weighted avg       0.72      0.70      0.70       132

Accuracy:
 0.696969696969697
ErrorRate:
 0.303030303030303
Cohen Kappa score:
 0.3548387096774194
----------------------------
split No: 2
----------------------------
Confusion Matrix:
 [[47 10]
 [19 56]]
classification report:

              precision    recall  f1-score   support

           0       0.71      0.82      0.76        57
           1       0.85      0.75      0.79        75

    accuracy                           0.78       132
   macro avg       0.78      0.79      0.78       132
weighted avg       0.79      0.78      

C:\Users\Ahmadi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ahmadi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ahmadi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [6]:
#predicting by applying BootStrap sampling method
from sklearn.utils import resample
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
url ='C:/Users/Ahmadi/OneDrive/Desktop/datasets/1.1 titanic.csv'
df = pd.read_csv(url).fillna(0)
#data cleaning , dropping column
df = df.drop('Name',axis=1)
df = df.drop('SexCode',axis=1)
#create mapper
PClass_mapper = {'1st':1,'2nd':2,'3rd':3}
gender_mapper = {'female':1,'male':2}

#replacing feature values with scale
df['PClass'] = df['PClass'].replace(PClass_mapper)
df['Sex'] = df['Sex'].replace(gender_mapper)
#replacing missing values of age with mean of age
df['Age'] = np.where(df['Age']==0,np.mean(df['Age']),df['Age'])
#input features
x = df.iloc[:,:3].values
#output class
y = df.iloc[:, 3].values
# using resample() for BootStrap sampling and resampling the classes
x_resample, y_resample = resample(x,y,replace=True,random_state=0)
x_train,x_test,y_train,y_test = train_test_split(x_resample,y_resample,test_size=0.3,random_state=0)
rfc = RandomForestClassifier(n_estimators=10)
rfc.fit(x_train,y_train)
y_pred = rfc.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, cohen_kappa_score
cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",cm)
error_rate = 1 - accuracy_score(y_test,y_pred)
print("classification report:\n")
print(classification_report(y_test,y_pred))
print('Accuracy:\n',accuracy_score(y_test,y_pred))
print('ErrorRate:\n',error_rate)
print('Cohen Kappa score:\n',cohen_kappa_score(y_test,y_pred))

Confusion Matrix:
 [[268  17]
 [ 37  72]]
classification report:

              precision    recall  f1-score   support

           0       0.88      0.94      0.91       285
           1       0.81      0.66      0.73       109

    accuracy                           0.86       394
   macro avg       0.84      0.80      0.82       394
weighted avg       0.86      0.86      0.86       394

Accuracy:
 0.8629441624365483
ErrorRate:
 0.13705583756345174
Cohen Kappa score:
 0.6369902746971506
